### PR TITLE
W13-Project-express-api-Yia

### PR DESCRIPTION
**Pull request by Citronskal**
## Netlify link
https://yia-project-express-api.onrender.com/ 

## Collaborators
solo

### CODE REVIEW

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
Hi Yia, please remove any form of authentication to access your API so that I can review it :)

**Comment by Citronskal** [comment]
Hi @AntonellaMorittu  thank you for reminding, i have removed it

**Comment by AntonellaMorittu** [comment]
still unauthorised, did you manually deployed the service again? 🤔

**Comment by Citronskal** [comment]
I manually deployed: https://yia-project-express-api.onrender.com Let me know if it doesn't work!

**Review by AntonellaMorittu — APPROVED** [review]

**Pull request closed without merging**
